apiVersion: v1
kind: Service
metadata:
  name: miccore-cleanarchitecture-adminer
  namespace: miccore-cleanarchitecture
  labels:
    group: db
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: miccore-cleanarchitecture-adminer
