apiVersion: v1
kind: Service
metadata:
  name: cleanarchitecture-sample
  labels:
    app: cleanarchitecture-sample
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: cleanarchitecture-sample